__author__ = "Lou-Poueyou Alexandre | github.com/AlexLoup33"

departementLinks =  {
    'Ain - 01' : "https://www.verif.com/top/revenue-r0/france-rcoun/auvergne-rhone-alpes-rreg/ain-rdep/", 'Aisne - 02' : "https://www.verif.com/top/revenue-r0/france-rcoun/hauts-de-france-rreg/aisne-rdep/",
    'Allier - 03' : "https://www.verif.com/top/revenue-r0/france-rcoun/auvergne-rhone-alpes-rreg/allier-rdep/", 'Alpes de Haute Provence - 04' : "https://www.verif.com/top/revenue-r0/france-rcoun/provence-alpes-cote-d-azur-rreg/alpes-de-haute-provence-rdep/",
    'Hautes-Alpes - 05' : "https://www.verif.com/top/revenue-r0/france-rcoun/provence-alpes-cote-d-azur-rreg/hautes-alpes-rdep/", 'Alpes Maritimes - 06' : "https://www.verif.com/top/revenue-r0/france-rcoun/provence-alpes-cote-d-azur-rreg/alpes-maritimes-rdep/",
    'Ardèche - 07' : "https://www.verif.com/top/revenue-r0/france-rcoun/auvergne-rhone-alpes-rreg/ardeche-rdep/", 'Ardennes - 08' : "https://www.verif.com/top/revenue-r0/france-rcoun/grand-est-rreg/ardennes-rdep/",
    'Ariège - 09' : "https://www.verif.com/top/revenue-r0/france-rcoun/occitanie-rreg/ariege-rdep/", 'Aube - 10' : "https://www.verif.com/top/revenue-r0/france-rcoun/grand-est-rreg/aube-rdep/",
    'Aude - 11' : "https://www.verif.com/top/revenue-r0/france-rcoun/occitanie-rreg/aude-rdep/", 'Aveyron - 12' : "https://www.verif.com/top/revenue-r0/france-rcoun/occitanie-rreg/aveyron-rdep/",
    'Bouches du Rhône - 13' : "https://www.verif.com/top/revenue-r0/france-rcoun/provence-alpes-cote-d-azur-rreg/bouches-du-rhone-rdep/", 'Calvados - 14' : "https://www.verif.com/top/revenue-r0/france-rcoun/normandie-rreg/calvados-rdep/",
    'Cantal - 15' : "https://www.verif.com/top/revenue-r0/france-rcoun/auvergne-rhone-alpes-rreg/cantal-rdep/", 'Charente - 16' : "https://www.verif.com/top/revenue-r0/france-rcoun/nouvelle-aquitaine-rreg/charente-rdep/",
    'Charente Maritime - 17' : "https://www.verif.com/top/revenue-r0/france-rcoun/nouvelle-aquitaine-rreg/charente-maritime-rdep/", 'Cher - 18' : "https://www.verif.com/top/revenue-r0/france-rcoun/centre-val-de-loire-rreg/cher-rdep/",
    'Corrèze - 19' : "https://www.verif.com/top/revenue-r0/france-rcoun/nouvelle-aquitaine-rreg/correze-rdep/", 'Corse du Sud - 2A' : "https://www.verif.com/top/revenue-r0/france-rcoun/corse-rreg/corse-du-sud-rdep/",
    'Haute Corse - 2B' : "https://www.verif.com/top/revenue-r0/france-rcoun/corse-rreg/haute-corse-rdep/", 'Côte d Or - 21' : "https://www.verif.com/top/revenue-r0/france-rcoun/bourgogne-franche-comte-rreg/cote-d-or-rdep/",
    'Côtes d Armor - 22' : "https://www.verif.com/top/revenue-r0/france-rcoun/bretagne-rreg/cote-d-armor-rdep/", 'Creuse - 23' : "https://www.verif.com/top/revenue-r0/france-rcoun/nouvelle-aquitaine-rreg/creuse-rdep/",
    'Dordogne - 24' : "https://www.verif.com/top/revenue-r0/france-rcoun/nouvelle-aquitaine-rreg/dordogne-rdep/", 'Doubs - 25' : "https://www.verif.com/top/revenue-r0/france-rcoun/bourgogne-franche-comte-rreg/doubs-rdep/",
    'Drôme - 26' : "https://www.verif.com/top/revenue-r0/france-rcoun/auvergne-rhone-alpes-rreg/drome-rdep/", 'Eure - 27' : "https://www.verif.com/top/revenue-r0/france-rcoun/normandie-rreg/eure-rdep/",
    'Eure et Loir - 28' : "https://www.verif.com/top/revenue-r0/france-rcoun/centre-val-de-loire-rreg/eure-et-loir-rdep/", 'Finistère - 29' : "https://www.verif.com/top/revenue-r0/france-rcoun/bretagne-rreg/finistere-rdep/",
    'Gard - 30' : "https://www.verif.com/top/revenue-r0/france-rcoun/occitanie-rreg/gard-rdep/", 'Haute Garonne - 31' : "https://www.verif.com/top/revenue-r0/france-rcoun/occitanie-rreg/haute-garonne-rdep/",
    'Gers - 32' : "https://www.verif.com/top/revenue-r0/france-rcoun/occitanie-rreg/gers-rdep/", 'Gironde - 33' : "https://www.verif.com/top/revenue-r0/france-rcoun/nouvelle-aquitaine-rreg/gironde-rdep/",
    'Hérault - 34' : "https://www.verif.com/top/revenue-r0/france-rcoun/occitanie-rreg/herault-rdep/", 'Ille et Vilaine - 35' : "https://www.verif.com/top/revenue-r0/france-rcoun/bretagne-rreg/ille-et-vilaine-rdep/",
    'Indre - 36' : "https://www.verif.com/top/revenue-r0/france-rcoun/centre-val-de-loire-rreg/indre-rdep/", 'Indre et Loire - 37' : "https://www.verif.com/top/revenue-r0/france-rcoun/centre-val-de-loire-rreg/indre-et-loire-rdep/",
    'Isère - 38' : "https://www.verif.com/top/revenue-r0/france-rcoun/auvergne-rhone-alpes-rreg/isere-rdep/", 'Jura - 39' : "https://www.verif.com/top/revenue-r0/france-rcoun/bourgogne-franche-comte-rreg/jura-rdep/",
    'Landes - 40' : "https://www.verif.com/top/revenue-r0/france-rcoun/nouvelle-aquitaine-rreg/landes-rdep/", 'Loir et Cher - 41' : "https://www.verif.com/top/revenue-r0/france-rcoun/centre-val-de-loire-rreg/loir-et-cher-rdep/",
    'Loire - 42' : "https://www.verif.com/top/revenue-r0/france-rcoun/auvergne-rhone-alpes-rreg/loire-rdep/", 'Haute Loire - 43' : "https://www.verif.com/top/revenue-r0/france-rcoun/auvergne-rhone-alpes-rreg/haute-loire-rdep/",
    'Loire Atlantique - 44' : "https://www.verif.com/top/revenue-r0/france-rcoun/pays-de-la-loire-rreg/loire-atlantique-rdep/", 'Loiret - 45' : "https://www.verif.com/top/revenue-r0/france-rcoun/centre-val-de-loire-rreg/loiret-rdep/",
    'Lot - 46' : "https://www.verif.com/top/revenue-r0/france-rcoun/occitanie-rreg/lot-rdep/", 'Lot et Garonne - 47' : "https://www.verif.com/top/revenue-r0/france-rcoun/nouvelle-aquitaine-rreg/lot-et-garonne-rdep/",
    'Lozère - 48' : "https://www.verif.com/top/revenue-r0/france-rcoun/occitanie-rreg/lozere-rdep/", 'Maine et Loire - 49' : "https://www.verif.com/top/revenue-r0/france-rcoun/pays-de-la-loire-rreg/maine-et-loire-rdep/",
    'Manche - 50' : "https://www.verif.com/top/revenue-r0/france-rcoun/normandie-rreg/manche-rdep/", 'Marne - 51' : "https://www.verif.com/top/revenue-r0/france-rcoun/grand-est-rreg/marne-rdep/",
    'Haute Marne - 52' : "https://www.verif.com/top/revenue-r0/france-rcoun/grand-est-rreg/haute-marne-rdep/", 'Mayenne - 53' : "https://www.verif.com/top/revenue-r0/france-rcoun/pays-de-la-loire-rreg/mayenne-rdep/",
    'Meurthe et Moselle - 54' : "https://www.verif.com/top/revenue-r0/france-rcoun/grand-est-rreg/meurthe-et-moselle-rdep/", 'Meuse - 55' : "https://www.verif.com/top/revenue-r0/france-rcoun/grand-est-rreg/meuse-rdep/",
    'Morbihan - 56' : "https://www.verif.com/top/revenue-r0/france-rcoun/bretagne-rreg/morbihan-rdep/", 'Moselle - 57' : "https://www.verif.com/top/revenue-r0/france-rcoun/grand-est-rreg/moselle-rdep/",
    'Nièvre - 58' : "https://www.verif.com/top/revenue-r0/france-rcoun/bourgogne-franche-comte-rreg/nievre-rdep/", 'Nord - 59' : "https://www.verif.com/top/revenue-r0/france-rcoun/hauts-de-france-rreg/nord-rdep/",
    'Oise - 60' : "https://www.verif.com/top/revenue-r0/france-rcoun/hauts-de-france-rreg/oise-rdep/", 'Orne - 61' : "https://www.verif.com/top/revenue-r0/france-rcoun/normandie-rreg/orne-rdep/",
    'Pas de Calais - 62' : "https://www.verif.com/top/revenue-r0/france-rcoun/hauts-de-france-rreg/pas-de-calais-rdep/", 'Puy de Dôme - 63' : "https://www.verif.com/top/revenue-r0/france-rcoun/auvergne-rhone-alpes-rreg/puy-de-dome-rdep/",
    'Pyrénées Atlantiques - 64' : "https://www.verif.com/top/revenue-r0/france-rcoun/nouvelle-aquitaine-rreg/pyrenees-atlantiques-rdep/", 'Hautes Pyrénées - 65' : "https://www.verif.com/top/revenue-r0/france-rcoun/occitanie-rreg/hautes-pyrenees-rdep/",
    'Pyrénées Orientales - 66' : "https://www.verif.com/top/revenue-r0/france-rcoun/occitanie-rreg/pyrenees-orientales-rdep/", 'Bas Rhin - 67' : "https://www.verif.com/top/revenue-r0/france-rcoun/grand-est-rreg/bas-rhin-rdep/",
    'Haut Rhin - 68' : "https://www.verif.com/top/revenue-r0/france-rcoun/grand-est-rreg/haut-rhin-rdep/", 'Rhône - 69' : "https://www.verif.com/top/revenue-r0/france-rcoun/auvergne-rhone-alpes-rreg/rhone-rdep/",
    'Haute Saône - 70' : "https://www.verif.com/top/revenue-r0/france-rcoun/bourgogne-franche-comte-rreg/haute-saone-rdep/", 'Saône et Loire - 71' : "https://www.verif.com/top/revenue-r0/france-rcoun/bourgogne-franche-comte-rreg/saone-et-loire-rdep/",
    'Sarthe - 72' : "https://www.verif.com/top/revenue-r0/france-rcoun/pays-de-la-loire-rreg/sarthe-rdep/", 'Savoie - 73' : "https://www.verif.com/top/revenue-r0/france-rcoun/auvergne-rhone-alpes-rreg/savoie-rdep/",
    'Haute Savoie - 74' : "https://verif.com/top/revenue-r0/france-rcoun/auvergne-rhone-alpes-rreg/haute-savoie-rdep/", 'Paris - 75' : "https://www.verif.com/top/revenue-r0/france-rcoun/ile-de-france-rreg/paris-rdep/",
    'Seine Maritime - 76' : "https://www.verif.com/top/revenue-r0/france-rcoun/normandie-rreg/seine-maritime-rdep/", 'Seine et Marne - 77' : "https://www.verif.com/top/revenue-r0/france-rcoun/ile-de-france-rreg/seine-et-marne-rdep/",
    'Yvelines - 78' : "https://www.verif.com/top/revenue-r0/france-rcoun/ile-de-france-rreg/yvelines-rdep/", 'Deux Sèvres - 79' : "https://www.verif.com/top/revenue-r0/france-rcoun/nouvelle-aquitaine-rreg/deux-sevres-rdep/",
    'Somme - 80' : "https://www.verif.com/top/revenue-r0/france-rcoun/hauts-de-france-rreg/somme-rdep/", 'Tarn - 81' : "https://www.verif.com/top/revenue-r0/france-rcoun/occitanie-rreg/tarn-rdep/",
    'Tarn et Garonne - 82' : "https://www.verif.com/top/revenue-r0/france-rcoun/occitanie-rreg/tarn-et-garonne-rdep/", 'Var - 83' : "https://www.verif.com/top/revenue-r0/france-rcoun/provence-alpes-cote-d-azur-rreg/var-rdep/",
    'Vaucluse - 84' : "https://www.verif.com/top/revenue-r0/france-rcoun/provence-alpes-cote-d-azur-rreg/vaucluse-rdep/", 'Vendée - 85' : "https://www.verif.com/top/revenue-r0/france-rcoun/pays-de-la-loire-rreg/vendee-rdep/",
    'Vienne - 86' : "https://www.verif.com/top/revenue-r0/france-rcoun/nouvelle-aquitaine-rreg/vienne-rdep/", 'Haute Vienne - 87' : "https://www.verif.com/top/revenue-r0/france-rcoun/nouvelle-aquitaine-rreg/haute-vienne-rdep/",
    'Vosges - 88' : "https://www.verif.com/top/revenue-r0/france-rcoun/grand-est-rreg/vosges-rdep/", 'Yonne - 89' : "https://www.verif.com/top/revenue-r0/france-rcoun/bourgogne-franche-comte-rreg/yonne-rdep/",
    'Territoire de Belfort - 90' : "https://www.verif.com/top/revenue-r0/france-rcoun/bourgogne-franche-comte-rreg/territoire-de-belfort-rdep/", 'Essonne - 91' : "https://www.verif.com/top/revenue-r0/france-rcoun/ile-de-france-rreg/essonne-rdep/",
    'Hauts de Seine - 92' : "https://www.verif.com/top/revenue-r0/france-rcoun/ile-de-france-rreg/hauts-de-seine-rdep/", 'Seine Saint Denis - 93' : "https://www.verif.com/top/revenue-r0/france-rcoun/ile-de-france-rreg/seine-saint-denis-rdep/",
    'Val de Marne - 94' : "https://www.verif.com/top/revenue-r0/france-rcoun/ile-de-france-rreg/val-de-marne-rdep/", 'Val d Oise - 95' : "https://www.verif.com/top/revenue-r0/france-rcoun/ile-de-france-rreg/val-d-oise-rdep/",
    'Guadeloupe - 971' : "https://www.verif.com/top/revenue-r0/france-rcoun/dom-rreg/guadeloupe-rdep/", 'Martinique - 972' : "https://www.verif.com/top/revenue-r0/france-rcoun/dom-rreg/martinique-rdep/",
    'Guyane - 973' : "https://www.verif.com/top/revenue-r0/france-rcoun/dom-rreg/guyane-rdep/", 'La Réunion - 974' : "https://www.verif.com/top/revenue-r0/france-rcoun/dom-rreg/la-reunion-rdep/",
    'Mayotte - 976' : "https://www.verif.com/top/revenue-r0/france-rcoun/dom-rreg/mayotte-rdep/"
}

ActivityLinks = {
   "Activité administrative et autres services de soutien aux entreprises": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/82-activites-administratives-et-autres-activites-de-soutien-aux-entreprises-rind/",
   "Activités de location et location-bail": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/77-activites-de-location-et-location-bail-rind/",
   "Activités des agences de voyage, voyagistes, services de réservation et activités connexes": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/79-activites-des-agences-de-voyage-voyagistes-services-de-reservation-et-activites-connexes-rind/",
   "Activités liées à l'emploi": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/78-activites-liees-a-l-emploi-rind/",
   "Enquêtes et sécurité": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/80-enquetes-et-securite-rind/",
   "Services relatifs aux bâtiments et aménagement paysager": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/81-service-relatifs-aux-betiments-et-amenagement-paysager-rind/",
   "Activités des organisations et organismes extraterritoriaux": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/99-activites-des-organisations-et-organismes-extraterritoriaux-rind/",
   "Activité auxiliaires de services financiers et d'assurance": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/66-activites-auxiliaires-de-services-financiers-et-d-assurance-rind/",
   "Activités des services financiers, hors assurance et caisses de retraite": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/64-activites-des-services-financiers-hors-assurance-et-caisses-de-retraite-rind/",
   "Assurance": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/65-assurance-rind/",
   "Activités immobilières": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/68-activites-immobilieres-rind/",
   "Activités d'architecture et d'ingénierie; activités de contrôle et analyses techniques": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/71-activites-d-architecture-et-d-ingenierie--activites-de-controle-et-analyses-techniques-rind/",
   "Activités des sièges sociaux; conseil de gestion": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/70-activites-des-sieges-sociaux--conseil-de-gestion-rind/",
   "Activités juridiques et comptables": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/69-activites-juridiques-et-comptables-rind/",
   "Activités vétérinaires": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/75-activites-veterinaires-rind/",
   "Autres activités spécialisées, scientifiques et techniques": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/74-autres-activites-specialisees-scientifiques-et-techniques-rind/",
   "Publicité et études de marché": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/73-publicite-et-etudes-de-marche-rind/",
   "Recherche et développement": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/72-recherche-developpement-scientifique-rind/",
   "Administration publique et défense; sécurité sociale obligatoire": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/84-administration-publique-et-defense--securite-sociale-obligatoire-rind/",
   "Culture et production animale, chasse et services annexes": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/01-culture-et-production-animale-chasse-et-services-annexes-rind/",
   "Pêche et aquaculture": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/03-peche-et-aquaculture-rind/",
   "Sylviculture et exploitation forestière": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/02-sylviculture-et-exploitation-forestiere-rind/",
   "Activités créatives, artistiques et de spectacle": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/90-activites-creatives-artistiques-et-de-spectacle-rind/",
   "Activités sportives, récréatives et de loisirs": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/93-activites-sportives-recreatives-et-de-loisirs-rind/",
   "Bibliothèques, archives, musées et autres activités culturelles": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/91-bibliotheques-archives-musees-et-autres-activites-culturelles-rind/",
    "Organisation de jeux de hasard et d'argent": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/92-organisation-de-jeux-de-hasard-et-d-argent-rind/",
    "Activités des organisations associatives": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/94-activites-des-organisation-associatives-rind/",
    "Autres services personnels": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/96-autres-services-personnels-rind/",
    "Réparation d'ordinateurs et de biens personnels et domestiques": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/95-reparation-d-ordinateurs-et-de-biens-personnels-et-domestiques-rind/",
    "Commerce de détail, à l'exception des automobiles et des motocycles": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/47-commerce-de-detail-a-l-exception-des-automobiles-et-des-motocycles-rind/",
    "Commerce de gros, à l'exception des automobiles et des motocycles": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/46-commerce-de-gros-a-l-exception-des-automobiles-et-des-motocycles-rind/",
    "Commerce et réparation d'automobiles et de motocycles": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/45-commerce-et-reparation-d-automobiles-et-de-motocycles-rind/",
    "Construction de bâtiments": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/41-construction-de-betiments-rind/",
    "Génie civil": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/42-genie-civil-rind/",
    "Travaux de construction spécialisés": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/43-travaux-de-construction-specialises-rind/",
    "Enseignement": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/85-enseignement-rind/",
    "Hébergement": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/55-hebergement-rind/",
    "Restauration": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/56-restauration-rind/",
    "Autres industries manufacturières": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/32-autres-industries-manufacturieres-rind/",
    "Cokéfaction et raffinage": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/19-cokefaction-et-raffinage-rind/",
    "Fabrication d'autres produits minéraux non métalliques": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/23-fabrication-d-autres-produits-mineraux-non-metalliques-rind/",
    "Fabrication d'autres matériels de transport": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/30-fabrication-d-autres-materiels-de-transport-rind/",
    "Fabrication d'équipements électriques": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/27-fabrication-d-equipements-electriques-rind/",
    "Fabrication de boissons": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/11-fabrication-de-boissons-rind/",
    "Fabrication de machines et équipements n.c.a.": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/28-fabrication-de-machines-et-equipements-n.c.a-rind",
    "Fabrication de meubles": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/31-fabrication-de-meubles-rind/",
    "Fabrication de produits à base de tabac": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/12-fabrication-de-produits-a-base-de-tabac-rind/",
    "Fabrication de produits en caoutchouc et en plastique": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/22-fabrication-de-produits-en-caoutchouc-et-en-plastique-rind/",
    "Fabrication de produits informatiques, électroniques et optiques": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/26-fabrication-de-produits-informatiques-electroniques-et-optiques-rind/",
    "Fabrication de produits métalliques, à l'exception des machines et des équipements": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/25-fabrication-de-produits-metalliques-a-l-exception-des-machines-et-des-equipements-rind/",
    "Fabrication de textiles": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/13-fabrication-de-textiles-rind/",
    "Imprimerie et reproduction d'enregistrements": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/18-imprimerie-et-reproduction-d-enregistrements-rind/",
    "Industrie automobile": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/29-industrie-automobile-rind/",
    "Industrie chimique": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/20-industrie-chimique-rind/",
    "Industrie de l'habillement": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/14-industrie-de-l-habillement-rind/",
    "Industrie du cuir et de la chaussure": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/15-industrie-du-cuir-et-de-la-chaussure-rind/",
    "Industrie du papier et du carton": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/17-industrie-du-papier-et-du-carton-rind/",
    "Industrie pharmaceutique": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/21-industrie-pharmaceutique-rind/",
    "Industries alimentaires": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/10-industries-alimentaires-rind/",
    "Métallurgie": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/24-metallurgie-rind/",
    "Réparation et installation de machines et d'équipements": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/33-reparation-et-installation-de-machines-et-d-equipements-rind/",
    "Travail du bois et fabrication d'articles en bois et en liège, sauf meubles; fabrication d'articles en vannerie et sparterie": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/16-travail-du-bois-et-fabrication-d-articles-en-bois-et-en-liege-a-l-exception-des-meubles--fabrication-d-articles-en-vannerie-et-sparterie-rind/",
    "Autres industries extractives": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/08-autres-industries-extractives-rind/",
    "Extraction d'hydrocarbures": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/06-extraction-d-hydrocarbures-rind/",
    "Extraction de houille et de lignite": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/05-extraction-de-houille-et-de-lignite-rind/",
    "Extraction de minerais métalliques": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/07-extraction-de-minerais-metalliques-rind/",
    "Services de soutien aux industries extractives": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/09-services-de-soutien-aux-industries-extractives-rind/",
    "Edition" : "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/58-edition-rind/",
    "Production de films cinématographiques, de vidéo et de programmes de télévision; enregistrement sonore et édition musicale": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/59-production-de-films-cinematographiques-de-video-et-de-programmes-de-television--enregistrement-sonore-et-edition-musicale-rind/",
    "Programmation et diffusion": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/60-programmation-et-diffusion-rind/",
    "Programmation, conseil et autres activités informatiques": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/62-programmation-conseil-et-autres-activites-informatiques-rind/",
    "Services d'information": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/63-services-d-information-rind/",
    "Télécommunications": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/61-telecommunications-rind/",
    "Captage, traitement et distribution d'eau": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/36-captage-traitement-et-distribution-d-eau-rind/",
    "Collecte et traitement des eaux usées": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/37-collecte-et-traitement-des-eaux-usees-rind/",
    "Collecte, traitement et élimination des déchets; récupération": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/38-collecte-traitement-et-elimination-des-dechets--recuperation-rind/",
    "Dépollution et autres services de gestion des déchets": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/39-depollution-et-autres-services-de-gestion-des-dechets-rind/",
    "Production et distribution d'électricité, de gaz, de vapeur et d'air conditionné": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/35-production-et-distribution-d-electricite-de-gaz-de-vapeur-et-d-air-conditionne-rind/",
    "Action sociale sans hébergement": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/88-action-sociale-sans-hebergement-rind/",
    "Activités pour la santé humaine": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/86-activites-pour-la-sante-humaine-rind/",
    "Hébergement médico-social et social": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/87-hebergement-medico-social-et-social-rind/",
    "Activités de poste et de courrier": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/53-activites-de-poste-et-de-courrier-rind/",
    "Entreposage et services auxiliaires des transports": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/52-entreposage-et-services-auxiliaires-des-transports-rind/",
    "Transports aériens": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/51-transports-aeriens-rind/",
    "Transports par eau": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/50-transports-par-eau-rind/",
    "Transports terrestres et transport par conduites": "https://www.verif.com/top/activity-sector-as0/revenue-r0/france-rcoun/49-transports-terrestres-et-transport-par-conduites-rind/",
}